package com.tenx.universalbanking.transactionmanager.enums;

public enum BacsDCPaymentStatus {

  PAYMENT_IN_PROGRESS,
  FAILED,
  COMPLETE,
  PROCESSOR_FAILED_COMPLETE,
  SUB_NOT_FOUND_COMPLETE,
  SUB_NOT_ACTIVE_COMPLETE,
  ACC_CLOSED_COMPLETE,
  NEW,
  PROCESSOR_FAILED_NEW,
  PROCESSOR_FAILED_APPLIED,
  SUB_NOT_FOUND_NEW,
  SUB_NOT_FOUND_APPLIED,
  RETURN_MATCHED,
  SUB_NOT_ACTIVE_NEW,
  SUB_NOT_ACTIVE_APPLIED,
  ACC_CLOSED_NEW,
  ACC_CLOSED_APPLIED,
  INVALID,
  RECALLED,
  UNMATCHED
}