package com.tenx.universalbanking.transactionmanager.enums;

public enum BacsDDStatusReason {

  MANDATE_NOT_FOUND,
  MANDATE_NOT_ACTIVE,
  PROCESSING_DATE_NOT_APPLICABLE,
  TO_PROCESS,
  DUPLICATE_FOUND,
  FIRST_ATTEMPT_UNAVAILABLE_BALANCE,
  SECOND_ATTEMPT_UNAVAILABLE_BALANCE,
  PROCESSED,
  SUB_NOT_FOUND_NEW,
  SUB_NOT_ACTIVE_NEW,
  DD_IN_REVERSAL
}
