/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package lbg.example.kafkasemantics.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
@Data
public class LineItem {

  @JsonProperty("ItemCode")
  private String itemCode;
  @JsonProperty("ItemDescription")
  private String itemDescription;
  @JsonProperty("ItemPrice")
  private Double itemPrice;
  @JsonProperty("ItemQty")
  private Integer itemQty;
  @JsonProperty("totalValue")
  private Double totalValue;

}
