/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package lbg.example.kafkasemantics.models;


import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Notification {

  @JsonProperty("InvoiceNumber")
  private String invoiceNumber;
  @JsonProperty("CustomerCardNo")
  private String customerCardNo;
  @JsonProperty("TotalAmount")
  private Double totalAmount;
  @JsonProperty("EarnedLoyaltyPoints")
  private Double earnedLoyaltyPoints;

}
