/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package lbg.example.kafkasemantics.models;


import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.ArrayList;
import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class PosInvoice {

  @JsonProperty("InvoiceNumber")
  private String invoiceNumber;
  @JsonProperty("CreatedTime")
  private Long createdTime;
  @JsonProperty("StoreID")
  private String storeID;
  @JsonProperty("PosID")
  private String posID;
  @JsonProperty("CashierID")
  private String cashierID;
  @JsonProperty("CustomerType")
  private String customerType;
  @JsonProperty("CustomerCardNo")
  private String customerCardNo;
  @JsonProperty("TotalAmount")
  private Double totalAmount;
  @JsonProperty("NumberOfItems")
  private Integer numberOfItems;
  @JsonProperty("PaymentMethod")
  private String paymentMethod;
  @JsonProperty("TaxableAmount")
  private Double taxableAmount;
  @JsonProperty("CGST")
  private Double cGST;
  @JsonProperty("SGST")
  private Double SGST;
  @JsonProperty("CESS")
  private Double CESS;
  @JsonProperty("DeliveryType")
  private String deliveryType;
  @JsonProperty("DeliveryAddress")
  private DeliveryAddress deliveryAddress;
  @JsonProperty("InvoiceLineItems")
  private List<LineItem> invoiceLineItems = new ArrayList<LineItem>();

}
