= Decisions

The following table details the key decisions that have been made about the project to date.  When a key decision has
been reached then a summary should be placed in the table below with a link to to a detail page.

* *Ref* - A unique reference value that links to the decision detail.
* *Date* - The date when the decision was made.
* *Contact* - The name of the team member that championed the decision within the project.
* *Title* - A meaningful name given to the decision and can be used in project activities and meetings.
* *Summary* - A small description/bullet points of the decision.  Communicates the key points of the decision.

|===
| Ref | Date | Contact | Title | Summary

| link:https://confluence.10x.mylti3gh7p4x.net/x/3xJvAg[REF-0]
| 2018/04/25
| Miles Wilson
| ARCH-DEC-0033 Use of sync/async api between transaction manager/platform payment manager and transaction manager
| Commercial COTS product  and Jenkins are the clear front runners in terms of requirements to functionality mapping matrix. Though Jenkins is not a formal tool for job scheduling, it provides the capability for job scheduling along with Dashboard and GUI.
|===
