apiVersion: v1
kind: Pod
metadata:
  name: cardrails-sql
  namespace: cards
spec:
  containers:
    - name: cockroach-sql
      image: 786796192785.dkr.ecr.eu-west-1.amazonaws.com/10x/cockroachsql:latest
      imagePullPolicy: Always
      command: ["sleep", "infinity"]
      envFrom:
        - configMapRef:
            name: cardrails-cru
      volumeMounts:
        - name: cockroach-certs
          mountPath: /cockroach-certs
  volumes:
    - name: cockroach-certs
      secret:
        secretName: cardrails-cru
        defaultMode: 256
  terminationGracePeriodSeconds: 0