downstream:
  interest-calculator:
    rest:
      url: https://interestcalculator-corebanking.svc.solution-testblue.mylti3gh7p4x.net
  payment-decision:
    rest:
      url: https://paymentdecisionframework-corepayments.svc.solution-testblue.mylti3gh7p4x.net
  payment-proxy:
    rest:
      url: https://paymentproxy-corepayments.svc.solution-testblue.mylti3gh7p4x.net
  worldpay-adapter:
    rest:
      url: https://worldpayadapter-corepayments.svc.solution-testblue.mylti3gh7p4x.net
  ledger-manager:
    rest:
      url: https://ledgermanager-corebanking.svc.solution-testblue.mylti3gh7p4x.net
  fam:
    rest:
      url: https://fundaccountmanager-cards.svc.solution-testblue.mylti3gh7p4x.net
  platform-payment-manager:
    rest:
      url: https://platformpaymentmanager-corepayments.svc.devblue.mylti3gh7p4x.net


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tm?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-interceptors: ConnectionState;StatementFinalizer;ResetAbandonedTimer
    h2:
      console:
        enabled: true

kafka:
  bootstrap:
    servers: localhost:9092
  security.protocol: PLAINTEXT
  api:
    key: apiKey
    password: apiPassword

reconciliation:
    log:
     console: false
     db: LOCAL_DB