microservice:
  replicaCount: 3
  namespace: cards
  nameOverride: cardrails

  image:
    repository: card-rails
    tag: __TAG__

  service:
    targetPort: 8080

  resources:
    limits:
      memory: 1.5Gi
    requests:
      memory: 1Gi

  cockroachdb:
    user: cardrails
    dbname: cardrailsdb
