spring:
  redis:
    host: localhost
    password:
    ssl: false
  datasource:
    url: jdbc:postgresql://localhost:26257/cardrailsdb?sslmode=disable
    username: root

kafka:
  ssl:
    algorithm: http
  sasl:
    mechanism:
    api:
      key:
      secret:
  security:
    protocol: PLAINTEXT
  schema:
    registry:
      url: "http://localhost:8081"
  bootstrap:
    servers: "http://localhost:9092"

downstream:
  debitcardmanager:
    host: "https://debitcardmanager-cards.svc.devblue.mylti3gh7p4x.net"
  feeschargescalculator:
    host: "https://feeschargescalculator2-corebankingb.svc.devblue.mylti3gh7p4x.net"
  ledgermanager:
    host: "https://ledgermanager-corebanking.svc.devblue.mylti3gh7p4x.net"
  subscriptionmanager2:
    host: "https://subscriptionmanager2-interaction.svc.devblue.mylti3gh7p4x.net"
  cardrailskafkaconnect:
    host: "https://cardrailskafkaconnect-cards.svc.devblue.mylti3gh7p4x.net"

hashpan:
  saltKey: "1234"

cardAuthSourceConnector:
  cronExpression: "0 */1 * * * *"
